# Generated by Django 5.2.6 on 2025-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filhos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.PositiveIntegerField()),
                ('capacidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(related_name='rotas', to='filhos.filho')),
            ],
        ),
    ]
